jwt:
  secretKey: mySuperSecretKey123456789!@#secure

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: OrdersLoggingFilter
            - name: Authentication
              args:
                isEnabled: true
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - name: Authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/