management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 5s
    instances:
      inventoryRetry:
        base-retry-config: default

  rate-limiter:
    instances:
      inventoryRateLimiter:
        limit-refresh-period: 5s
        limit-for-period: 1
        timeout-duration: 1s

  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 3
        event-consumer-buffer-size: 10
